apiVersion: v2
appVersion: "6.4.10.10"
description: A Helm chart for Collabora Office - CODE-Edition
name: collabora-code
version: 2.2.0
icon: https://avatars0.githubusercontent.com/u/22418908?s=200&v=4
sources:
- https://chrisingenhaag.github.io/helm/
maintainers:
- name: Christian
  email: christian.ingenhaag@googlemail.com
home: https://chrisingenhaag.github.io/helm/
